CREATE TABLE User (
	User_ID INT NOT NULL AUTO_INCREMENT,
	Firstname VARCHAR(100) NOT NULL,
	Lastname VARCHAR(100) NOT NULL,
	EmailAddress VARCHAR(100) NOT NULL,
	Password VARCHAR(100) NOT NULL,
	Group_ID INT NOT NULL,
	primary key (User_ID)
)